### PR TITLE
Feature: Unit tests

### PR DESCRIPTION
**Pull request by thinkverse**
Added unit tests via `@vue/cli` and went with `jest` instead of `mocha`, so now you can all write tests, added an example test for the `Landing.vue`.

### CODE REVIEW

**Comment by moxiegirl** [comment]
Stellar @thinkverse I'm asking @timstackblock our QA Engineer to take a look too.  He's got an amazing reviewer's eye.

**Comment by zone117x** [comment]
@timstackblock @thinkverse Can we get these tests running on CircleCI?

**Comment by thinkverse** [comment]
Probably if it's like Travis, can try it?

**Comment by thinkverse** [comment]
@zone117x @timstackblock So I got Circle-CI to work, though I'm not sure how the results work they all get skipped: `SKIPPED, file is empty` of course the file is empty from the beginning right, doesn't Circle add the results?

**Comment by thinkverse** [comment]
coverage seems to be working fine, test results artifact doesn't get saved though, anyone have any ideas?

**Comment by thinkverse** [comment]
Circle CI is now integrated, test results are logged, and the coverage is displaying as they should.

**Comment by kantai** [comment]
Yeah, let's do it

**Comment by kantai** [comment]
Should we add the coverage outputs to `.gitignore` and remove from the PR? They seem like they'll be kind of noisy in the git history.

**Comment by thinkverse** [comment]
If you want, can get on that is about an hour or so, making dinner atm,

**Comment by thinkverse** [comment]
And done and dusted. 😄

**Comment by kantai** [comment]
Great! Merging. Thanks @thinkverse

**Pull request merged**
